server:
  address: 0.0.0.0
  port: 8888

spring:
  application:
    name: liar
  datasource:
    url: "jdbc:mysql://localhost:3306/liar"
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  security:
    jwt:
      key: 'abcdefghijklmn'
      expire: 144
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    flow:
      period: 3
      limit: 50
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
