server:
  address: 0.0.0.0
  port: 8888

spring:
  application:
    name: liar
  datasource:
    url: "jdbc:mysql://localhost:3306/liar"
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    password: guest
